### PR TITLE
Add test targets of Ruby

### PR DESCRIPTION
**Pull request by kentarohorie**
Add test targets of Ruby 3.1, 3.2

### CODE REVIEW

**Comment by ashie** [comment]
Could you remove `2.4` and `2.5`?
We no longer support them since they are already EOL.
```
ERROR:  Error installing bundler:
	bundler requires Ruby version >= 2.6.0.
```

**Comment by kentarohorie** [comment]
I removed 2.4 ~ 2.6

It seems 2.6 is also eol
https://www.ruby-lang.org/en/downloads/branches/

**Comment by kentarohorie** [comment]
3.1.. 🤔 
I can't reproduce it in my environment.

```
docker pull ruby:3.1.3
docker run -it --rm ruby:3.1.3 bash

git clone https://github.com/fluent/fluent-logger-ruby.git
gem install bundler rake
bundle
bundle exec rake spec
```

result
```
root@7e3654e44045:/fluent-logger-ruby# bundle exec rake spec
/usr/local/bin/ruby -I/usr/local/bundle/gems/rspec-core-3.12.1/lib:/usr/local/bundle/gems/rspec-support-3.12.0/lib /usr/local/bundle/gems/rspec-core-3.12.1/exe/rspec spec/console_logger_spec.rb spec/fluent_logger_spec.rb spec/level_fluent_logger_spec.rb spec/logger_base_spec.rb spec/logger_spec.rb spec/null_logger_spec.rb spec/test_logger_spec.rb
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}
........................................................

Finished in 34.06 seconds (files took 0.70206 seconds to load)
56 examples, 0 failures
```

**Comment by ashie** [comment]
Yep, some tests seem unstable on Ruby 3.1 & 3.2.
We need to fix them (in another pull request).

**Comment by ashie** [comment]
Thanks!

**Comment by ashie** [comment]
Unstable tests are fixed in #96

**Pull request merged**
